name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
